version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: shakee2001
      POSTGRES_DB: online-course
      POSTGRES_PORT: 6008
  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: online-course
      DATABASE_USER: postgres
      DATABASE_PASSWORD: shakee2001
    ports:
      - "8080:8080"